### ISSUE TITLE
php prestashopConsole.phar  Fatal error: Uncaught Error: Class 'InfoCommand' 

### ISSUE THREAD

**Issue by mohamedaitbella** [nenes25/prestashop_console#239]
####  just after installation i try to run the command bellow and it gives a fatal error i tried two version  1.6.2  and 1.6.1 the same error occur
php prestashopConsole.phar

Fatal error: Uncaught Error: Class 'InfoCommand' not found in phar://C:/laragon/www/annonceslocal/prestashopConsole.phar/src/Hhennes/PrestashopConsole/PrestashopConsoleApplication.php:129
Stack trace:
#0 phar://C:/laragon/www/annonceslocal/prestashopConsole.phar/src/Hhennes/PrestashopConsole/PrestashopConsoleApplication.php(94): Hhennes\PrestashopConsole\PrestashopConsoleApplication->registerCommands('install')
#1 phar://C:/laragon/www/annonceslocal/prestashopConsole.phar/bin/phar/consolePhar.php(39): Hhennes\PrestashopConsole\PrestashopConsoleApplication->registerInstallCommands()
#2 C:\laragon\www\annonceslocal\prestashopConsole.phar(10): require('phar://C:/larag...')
#3 {main}
  thrown in phar://C:/laragon/www/annonceslocal/prestashopConsole.phar/src/Hhennes/PrestashopConsole/PrestashopConsoleApplication.php on line 129

### PrestashopConsole Version 
1.6.2

### Prestashop Version
1.7.8.1

### Php Version
 7.4.11

**Comment by nenes25** [comment]
Hello @mohamedaitbella,

Thanks for your report, i've not tested recently the console with windows environments.
I'll try to check and let you know.
I'm not able to reproduce this issue for now.

Regards,
